---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: anomaly-detection
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
  - http:
      paths:
      - path: /anomaly-detection
        pathType: Prefix
        backend:
          service:
            name: anomaly-detection
            port: 
              number: 80
