apiVersion: v1
kind: ConfigMap
metadata:
  name: stress-test
data:
  test1.js: |
    import http from 'k6/http';
    import { check, sleep } from 'k6';

    export let options = {
      stages: [
        { duration: '30s', target: 20 },
        { duration: '1m30s', target: 10 },
        { duration: '20s', target: 0 },
      ],
    };

    export default function () {
      let res = http.get('https://api.dev.mobimeo.com/anomaly-detection/hello');
      check(res, { 'status was 200': (r) => r.status == 200 });
      sleep(1);
    }

---

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-test
spec:
  parallelism: 4
  script: 
    configMap:
      name: stress-test
      file: test1.js
  runner:
    resources:
      limits:
        cpu: "200m"
        memory: "200Mi"
      requests:
        cpu: "100m"
        memory: "200Mi"
