apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: anomaly-detection
  labels:
    app: anomaly-detection
spec:
  selector:
    matchLabels:
      app: anomaly-detection
  endpoints:
    - port: web
